# Generated by Django 2.0.2 on 2018-05-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('choice_a', models.TextField()),
                ('choice_b', models.TextField()),
                ('choice_c', models.TextField()),
                ('choice_d', models.TextField()),
                ('solution', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('score', models.PositiveSmallIntegerField()),
                ('add_time', models.DateTimeField(verbose_name='time added')),
                ('latest_modify_time', models.DateTimeField(verbose_name='time latest modified')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceQuestionAnswerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=1)),
                ('answer_time', models.DateTimeField(default=None, verbose_name='time answered')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.ChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('class_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='date starts')),
                ('end_time', models.DateTimeField(verbose_name='date ends')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TrueOrFalseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('solution', models.BooleanField()),
                ('score', models.PositiveSmallIntegerField()),
                ('add_time', models.DateTimeField(verbose_name='time added')),
                ('latest_modify_time', models.DateTimeField(verbose_name='time latest modified')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TrueOrFalseQuestionAnswerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=None)),
                ('answer_time', models.DateTimeField(default=None, verbose_name='time answered')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.TrueOrFalseQuestion')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Test')),
            ],
        ),
        migrations.AddField(
            model_name='choicequestionanswerrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Student'),
        ),
        migrations.AddField(
            model_name='choicequestionanswerrecord',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_test.Test'),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Teacher'),
        ),
    ]
