# Generated by Django 2.0.2 on 2018-05-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='ss', max_length=50),
            preserve_default=False,
        ),
    ]
