# Generated by Django 2.0.2 on 2018-05-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0002_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='score',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='score',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
