# Generated by Django 2.0.2 on 2018-05-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0003_auto_20180502_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestionanswerrecord',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestionanswerrecord',
            name='answer_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='time answered'),
        ),
    ]
