# Generated by Django 2.0.2 on 2018-05-02 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0004_auto_20180502_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Teacher'),
        ),
        migrations.AlterField(
            model_name='choicequestionanswerrecord',
            name='answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='choicequestionanswerrecord',
            name='answer_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='time answered'),
        ),
        migrations.AlterField(
            model_name='choicequestionanswerrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Student'),
        ),
        migrations.AlterField(
            model_name='test',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Teacher'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestion',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Teacher'),
        ),
        migrations.AlterField(
            model_name='trueorfalsequestionanswerrecord',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_test.Student'),
        ),
    ]
