# Generated by Django 2.0.2 on 2018-05-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_test', '0005_auto_20180502_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='choice_questions',
            field=models.ManyToManyField(blank=True, null=True, to='online_test.ChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='test',
            name='true_or_false_questions',
            field=models.ManyToManyField(blank=True, null=True, to='online_test.TrueOrFalseQuestion'),
        ),
    ]
